export const metadata = {
  title: 'Terms of Service — Substack Finder',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white px-4 py-12">
      <div className="mx-auto max-w-2xl">
        <a href="/" className="text-sm text-orange-600 hover:underline">
          &larr; Back to Substack Finder
        </a>
        <h1 className="mt-4 text-3xl font-bold text-gray-900">Terms of Service</h1>
        <p className="mt-1 text-sm text-gray-500">Last updated: July 17, 2026</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-gray-700">
          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">1. Overview</h2>
            <p>
              Substack Finder (&ldquo;the Service&rdquo;), operated by Stack Tools, helps Substack
              writers discover other creators to connect and collaborate with. By using the
              Service you agree to these Terms. If you don&rsquo;t agree, please don&rsquo;t use it.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">2. The service &amp; AI results</h2>
            <p>
              Matches are generated by AI using publicly available web information and are
              suggestions only. We don&rsquo;t guarantee their accuracy or completeness, that a
              listed creator is a good fit, or that anyone will respond to or agree to collaborate
              with you. The Service is provided on an &ldquo;as is&rdquo; basis.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">3. Your account</h2>
            <p>
              You&rsquo;re responsible for keeping your login details secure and for activity that
              happens under your account. Please provide accurate information when you sign up.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">4. Membership &amp; billing</h2>
            <p>
              A free plan is available. A paid membership is $9.99/month, billed through Stripe and
              renewing automatically until you cancel. You can cancel anytime, and your access
              continues until the end of the paid period. Except where required by law, we
              don&rsquo;t provide prorated refunds for partial periods.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">5. Acceptable use</h2>
            <p>
              Please don&rsquo;t misuse the Service — no automated scraping, attempts to overload or
              break it, reselling access, or any unlawful use.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">6. Third-party content</h2>
            <p>
              Links point to third-party Substack newsletters. We are not affiliated with,
              endorsed by, or responsible for Substack or any newsletter listed.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">7. Disclaimer &amp; liability</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
              fullest extent permitted by law, Stack Tools is not liable for any indirect,
              incidental, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">8. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after an
              update means you accept the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-1 text-lg font-semibold text-gray-900">9. Contact</h2>
            <p>
              Questions? Email us at{' '}
              <a href="mailto:stacktoolsinbox@gmail.com" className="text-orange-600 hover:underline">
                stacktoolsinbox@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
